name: Run tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout into Repository 
        uses: actions/checkout@v3

      - name: Setup Python and cache req
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4
          cache: pip

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python test_chainex.py
        shell: sh