name: Run tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout, Setup Python and cache req
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.4
          cache: pip
      - run: pip install -r requirements.txt

      - name: Run Tests
        run: python test_chainex.py
        shell: sh