name: Run tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout into Repository 
        uses: actions/checkout@v3

      - name: Setup Python and cache req
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: Cache Requirements
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python test_chainex.py
        shell: sh